### ISSUE TITLE
Retrying setup: Token exchange failed. Request status: 400

### ISSUE THREAD

**Issue by vladimirzrnic** [lendy007/homeassistant-skodaconnect#160] opened 2023-01-02 11:50 UTC
**Describe the bug**
Retrying setup: Token exchange failed. Request status: 400
![New Project](https://user-images.githubusercontent.com/69601702/210227184-9bf3eff3-b17a-4718-be8b-45ce9e19bf53.png)

**Debug logs**
2023-01-02 12:31:56.869 WARNING (MainThread) [homeassistant.config_entries] Config entry 'xxxxxxxxxxxxxxxxx' for skodaconnect integration not ready yet: Token exchange failed. Request status: 400; Retrying in background
2023-01-02 12:32:03.343 ERROR (MainThread) [skodaconnect.connection] An API error was encountered during login, try again later
2023-01-02 12:32:14.707 ERROR (MainThread) [skodaconnect.connection] An API error was encountered during login, try again later

**Installation:**
Home Assistant 2022.12.8
Supervisor 2022.12.1
Operating System 9.4
Frontend 20221213.1 - latest
Skoda Connect 1.1.4

Two days ago, I had a problem with the integration that suddenly stopped working. While debug log shows an API error was encountered during login, I could not trace the issue further. It doesn't look like a temporary problem with the Skoda/VW server, as it has been going on for 48 hours while their mobile app is still working.

**Comment by jvandijk** [comment] 2023-01-02 12:10
@vladimirzrnic this is a duplicate of #159

**Comment by Farfar** [comment] 2023-01-02 12:33
As jvandijk stated, duplicate.

**Closed by Farfar** 2023-01-02 12:33 UTC
Labels: bug
