### ISSUE TITLE
Can't start combustion heater after update

### ISSUE THREAD

**Issue by dennzs** [lendy007/homeassistant-skodaconnect#12] opened 2021-02-14 20:24 UTC
I just updated to 1.0.35 and the refactoring seems to work well and I get everything from lock status to mileage etc reported correctly. What doesn't seem to work is the heater action (the new switches). I have a 2019 Kodiaq and it all worked today before I updated to the new version. I'm pretty sure I was on 1.0.26 previously.

Car: 2019 Kodiaq
Skoda Connect: 1.0.35
HACS: 1.11.3
Home Assistant: 2021.2.3
I'm running on docker on a Raspberry Pi 4 on Ubuntu if it matters. The car shows 12 requests remaining.

The action fails almost immediately (Failed to call service switch/turn_on. Pre-heater action failed)
and this is shown in the log.

```
Logger: homeassistant.core
Source: custom_components/skodaconnect/switch.py:32
First occurred: 9:19:56 PM (1 occurrences)
Last logged: 9:19:56 PM

Error executing service: <ServiceCall switch.turn_on (c:226cb642c2122c0a0caaae89d21e718b): entity_id=['switch.kodiaq_parking_heater_heating']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1471, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1490, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 595, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 632, in _handle_entity_call
    await result
  File "/config/custom_components/skodaconnect/switch.py", line 32, in async_turn_on
    await self.instrument.turn_on()
  File "/usr/local/lib/python3.8/site-packages/skodaconnect/dashboard.py", line 526, in turn_on
    await self.vehicle.set_pheater(mode='heating', spin=self.spin)
  File "/usr/local/lib/python3.8/site-packages/skodaconnect/vehicle.py", line 431, in set_pheater
    raise Exception('Pre-heater action failed')
Exception: Pre-heater action failed
```

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/skodaconnect/switch.py:32
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:20:58 PM (2 occurrences)
Last logged: 9:54:35 PM

[281472847932768] Pre-heater action failed
[281472606411312] Pre-heater action failed
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 136, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1455, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1490, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 595, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 632, in _handle_entity_call
    await result
  File "/config/custom_components/skodaconnect/switch.py", line 32, in async_turn_on
    await self.instrument.turn_on()
  File "/usr/local/lib/python3.8/site-packages/skodaconnect/dashboard.py", line 526, in turn_on
    await self.vehicle.set_pheater(mode='heating', spin=self.spin)
  File "/usr/local/lib/python3.8/site-packages/skodaconnect/vehicle.py", line 431, in set_pheater
    raise Exception('Pre-heater action failed')
Exception: Pre-heater action failed
```

**Comment by dennzs** [comment] 2021-02-14 20:38
Tested other versions.

Reverted to 1.0.26 => Works
then
Upgraded to 1.0.30 => Works 
then
Upgraded to 1.0.35 => Fails
then
Reverted to 1.0.30 => Works

So it only seems to have broken between 30 and 35.

**Comment by Farfar** [comment] 2021-02-14 20:41
Yes, this is a duplicate of https://github.com/lendy007/skodaconnect/issues/7#issuecomment-778838199
Will push fix as soon as I can. For those who doesn't want to wait, the fix is outlined in linked issue.

**Comment by dennzs** [comment] 2021-02-14 20:47
My bad, hadn't refreshed the issue list before I posted 🤦

**Comment by Farfar** [comment] 2021-02-14 20:53
> My bad, hadn't refreshed the issue list before I posted 🤦

No problem, that issue is registered on the librarys github repo. Might as well leave this issue open for visibility intim this is fixed.

**Comment by Farfar** [comment] 2021-02-15 13:41
New release, please close issue if it is working.

**Closed** 2021-02-16 21:03 UTC
Labels: bug
