### ISSUE TITLE
problem with login

### ISSUE THREAD

**Issue by Mocky158** [lendy007/homeassistant-skodaconnect#119] opened 2022-05-06 19:05 UTC
Good day
I have a login problem always showing me just this simple login window. I've tried everything possible to delete the folder from custom compoment and re-add restart home assist but for now I will always stay on this window. No login will be performed when entering data.
I also tried anonymous chrome cuts.
Thank you for your help with the repair.

<img width="391" alt="Snímek obrazovky 2022-05-06 v 20 59 30" src="https://user-images.githubusercontent.com/90219705/167201600-07266e7e-d631-43f8-afc6-198c95e06790.png">

<img width="387" alt="Snímek obrazovky 2022-05-06 v 21 04 23" src="https://user-images.githubusercontent.com/90219705/167201803-e56e9af6-6106-4b2a-ab29-d0f7d5797799.png">

**Comment by Mocky158** [comment] 2022-05-13 04:47
I found these two mistakes. Or if I have to look elsewhere at the log, consult.
when I log in to skoda.connect then I don't see any confirmation of the condition.
Thank you, Zoul

<img width="752" alt="Snímek obrazovky 2022-05-13 v 6 33 45" src="https://user-images.githubusercontent.com/90219705/168212729-aafbe553-b30f-4c2c-a281-3336d1942fc4.png">
<img width="852" alt="Snímek obrazovky 2022-05-13 v 6 41 45" src="https://user-images.githubusercontent.com/90219705/168212748-fc35d4ee-b483-4b8c-bec6-2c0295fb18c0.png">
<img width="1171" alt="Snímek obrazovky 2022-05-13 v 6 37 17" src="https://user-images.githubusercontent.com/90219705/168212953-2ae55a34-0a75-4360-913c-af09ad63d827.png">

**Comment by Mocky158** [comment] 2022-05-18 05:49
I don't know if it was the problem but I did a new registration and settings of the car. With gmail.com and everything works. Previously used seznam.cz

**Comment by DLHN-cz** [comment] 2022-06-25 09:17
I have the same problem. Login failed due to "unaccepted" terms of condition. But app is running well and I accepted all of them on website. Nothing helped... Can anyone help me where to accept these terms?

**Comment by DLHN-cz** [comment] 2022-06-25 11:30
> I have the same problem. Login failed due to "unaccepted" terms of condition. But app is running well and I accepted all of them on website. Nothing helped... Can anyone help me where to accept these terms? `Tato chyba pochází z vlastní integrace.
> 
> Logger: custom_components.skodaconnect.config_flow Source: custom_components/skodaconnect/config_flow.py:99 Integration: Skoda Connect (documentation, issues) First occurred: 11:12:26 (1 occurrences) Last logged: 11:12:26
> 
> Login failed with error: The terms and conditions must be accepted first at "[https://www.skoda-connect.com/"`](https://www.skoda-connect.com/%22%60)

I tried complete uninstall and reinstall in HACS, but without success :( still the same error. Can anyone help, what to do?

**Comment by Farfar** [comment] 2022-06-25 11:36
Please try different browsers and/or clear cache and site data in the browser.
Most often Chrome won't show the new terms but other browsers will.

**Comment by Farfar** [comment] 2022-07-04 16:07
> > 
> 
> I tried it, but without a success :( By the clicking through the my web profile I found out, that my registration is in Germany, not in CR, but I suppose it shouldn't be problem, am I right?

No it should not. But if the integration reports that you need to accept eula then you need to accept eula. Have you tried log out and login in app? Or login in new device

**Comment by vaclav-steiner** [comment] 2022-07-18 12:14
Hi,

trying with new Škoda ID (registered today) and Škoda Karoq (with "Care connect - remote access" enabled) and same troubles with terms and conditions. Downgrading to older versions didn't help.

I tried to login to my Škoda profile with firefox, chrome, safari, edge - anonymous and nonanonymous mode. I was never able to reconfirm the terms and conditions :-(

**Comment by DLHN-cz** [comment] 2022-07-18 12:29
> 

Exactly, I tried also a bunch of browsers/modes. Also relogon into app and lot combinations. Everything without success.

**Comment by Farfar** [comment] 2022-07-18 19:27
For those of you still having issues and tried everything, please provide full debug logs. There might be clues prior to the terms and conditions error.

**Comment by vaclav-steiner** [comment] 2022-07-19 06:19
I set up debug like this:

> custom_components.skodaconnect: debug
> skodaconnect.connection: debug

and here is the output. I replaced the email and other hashes with "XXXXX". Hopefully it will help

```
2022-07-19 06:11:51 DEBUG (MainThread) [custom_components.skodaconnect.config_flow] Creating connection to Skoda Connect
2022-07-19 06:11:51 INFO (MainThread) [skodaconnect.connection] Init Skoda Connect library, version 1.1.20
2022-07-19 06:11:51 DEBUG (MainThread) [skodaconnect.connection] Using service https://msg.volkswagen.de
2022-07-19 06:11:51 INFO (MainThread) [skodaconnect.connection] Initiating new login
2022-07-19 06:11:51 DEBUG (MainThread) [skodaconnect.connection] Starting authorization process for client skoda
2022-07-19 06:11:52 DEBUG (MainThread) [skodaconnect.connection] Got redirect to signin-service
2022-07-19 06:11:52 DEBUG (MainThread) [skodaconnect.connection] Start authorization for user XXXXXXXXXXXXXX
2022-07-19 06:11:52 DEBUG (MainThread) [skodaconnect.connection] Found dynamic credentials form, extracting attributes
2022-07-19 06:11:52 DEBUG (MainThread) [skodaconnect.connection] JSON: {'clientLegalEntityModel': {'clientId': 'XXXXXXXXXXXXXX@apps_vw-dilab_com', 'clientAppName': 'ŠKODA App & Portal', 'clientAppDisplayName': 'ŠKODA App & Portal', 'legalEntityInfo': {'name': 'ŠKODA', 'shortName': 'SKODA', 'productName': 'ŠKODA ID', 'theme': 'skoda', 'defaultLanguage': 'cs', 'termAndConditionsType': 'DEFAULT', 'legalProperties': {'revokeDataContact': 'DPOffice@skoda-auto.cz', 'imprintText': 'IMPRINT', 'countryOfJurisdiction': 'CZ'}}, 'imprintTextKey': 'imprint.link.text'}, 'template': 'loginAuthenticate', 'hmac': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'useClientRendering': True, 'emailPasswordForm': {'@class': 'com.volkswagen.identitykit.signin.web.flows.base.model.EmailPasswordForm', 'email': 'XXXXXXXXXXXXXXXXXXXXX', 'password': None}, 'error': None, 'relayState': 'XXXXXXXXXXXXXXXXXXXXX', 'nextButtonDisabled': False, 'enableNextButtonAfterSeconds': 0, 'postAction': 'login/authenticate', 'identifierUrl': 'login/identifier'}
2022-07-19 06:11:52 DEBUG (MainThread) [skodaconnect.connection] Finalizing login
2022-07-19 06:11:53 WARNING (MainThread) [skodaconnect.connection] Login failed, the terms and conditions might have been updated and need to be accepted. Login to https://www.skoda-connect.com and accept the new terms before trying again
2022-07-19 06:11:53 ERROR (MainThread) [custom_components.skodaconnect.config_flow] Login failed with error: The terms and conditions must be accepted first at "https://www.skoda-connect.com/"
2022-07-19 06:13:11 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/skodaconnect/config_flow.py", line 102, in _async_task_login
    if result is False:
UnboundLocalError: local variable 'result' referenced before assignment
```

Thank you.

**Comment by Farfar** [comment] 2022-07-19 07:13
> I set up debug like this:
> 
> > custom_components.skodaconnect: debug
> > skodaconnect.connection: debug
> 
> and here is the output. I replaced the email and other hashes with "XXXXX". Hopefully it will help
> 
> ```
> 2022-07-19 06:11:51 DEBUG (MainThread) [custom_components.skodaconnect.config_flow] Creating connection to Skoda Connect
> 2022-07-19 06:11:51 INFO (MainThread) [skodaconnect.connection] Init Skoda Connect library, version 1.1.20
> 2022-07-19 06:11:51 DEBUG (MainThread) [skodaconnect.connection] Using service https://msg.volkswagen.de
> 2022-07-19 06:11:51 INFO (MainThread) [skodaconnect.connection] Initiating new login
> 2022-07-19 06:11:51 DEBUG (MainThread) [skodaconnect.connection] Starting authorization process for client skoda
> 2022-07-19 06:11:52 DEBUG (MainThread) [skodaconnect.connection] Got redirect to signin-service
> 2022-07-19 06:11:52 DEBUG (MainThread) [skodaconnect.connection] Start authorization for user XXXXXXXXXXXXXX
> 2022-07-19 06:11:52 DEBUG (MainThread) [skodaconnect.connection] Found dynamic credentials form, extracting attributes
> 2022-07-19 06:11:52 DEBUG (MainThread) [skodaconnect.connection] JSON: {'clientLegalEntityModel': {'clientId': 'XXXXXXXXXXXXXX@apps_vw-dilab_com', 'clientAppName': 'ŠKODA App & Portal', 'clientAppDisplayName': 'ŠKODA App & Portal', 'legalEntityInfo': {'name': 'ŠKODA', 'shortName': 'SKODA', 'productName': 'ŠKODA ID', 'theme': 'skoda', 'defaultLanguage': 'cs', 'termAndConditionsType': 'DEFAULT', 'legalProperties': {'revokeDataContact': 'DPOffice@skoda-auto.cz', 'imprintText': 'IMPRINT', 'countryOfJurisdiction': 'CZ'}}, 'imprintTextKey': 'imprint.link.text'}, 'template': 'loginAuthenticate', 'hmac': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'useClientRendering': True, 'emailPasswordForm': {'@class': 'com.volkswagen.identitykit.signin.web.flows.base.model.EmailPasswordForm', 'email': 'XXXXXXXXXXXXXXXXXXXXX', 'password': None}, 'error': None, 'relayState': 'XXXXXXXXXXXXXXXXXXXXX', 'nextButtonDisabled': False, 'enableNextButtonAfterSeconds': 0, 'postAction': 'login/authenticate', 'identifierUrl': 'login/identifier'}
> 2022-07-19 06:11:52 DEBUG (MainThread) [skodaconnect.connection] Finalizing login
> 2022-07-19 06:11:53 WARNING (MainThread) [skodaconnect.connection] Login failed, the terms and conditions might have been updated and need to be accepted. Login to https://www.skoda-connect.com and accept the new terms before trying again
> 2022-07-19 06:11:53 ERROR (MainThread) [custom_components.skodaconnect.config_flow] Login failed with error: The terms and conditions must be accepted first at "https://www.skoda-connect.com/"
> 2022-07-19 06:13:11 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/config/custom_components/skodaconnect/config_flow.py", line 102, in _async_task_login
>     if result is False:
> UnboundLocalError: local variable 'result' referenced before assignment
> ```
> 
> Thank you.

Thank you. I know where in the code it stops but I would need a full debug with response debugging enabled as well. That's done in the integration settings in Home Assistant.

**Comment by DLHN-cz** [comment] 2022-07-21 06:56
Yes, it's exactly the same for me. Can you kick me right way, how to enable the full debug with response as you mentioned?

**Comment by Farfar** [comment] 2022-07-21 07:03
It only works if the integration is already installed unfortunately. You got to Settings->Devices & Services->Configure for Skoda Connect.
![Screenshot_20220721-085856_Home Assistant](https://user-images.githubusercontent.com/1235384/180150719-5940f4e3-8702-4457-b6b5-4f79d1f88373.jpg)

Else you can use the library example code and try that one out. It will print all to console.

**Comment by vaclav-steiner** [comment] 2022-07-21 08:33
Hello a thank you for another gint. I tried to run simple code from console, using source code fromhttps://pypi.org/project/skodaconnect/1.1.21/, like this (i'm not good in python, sorry for mistakes]

``` python
#!/usr/bin/env python3
import pprint
import asyncio
import logging

from skodaconnect.connection import Connection
from aiohttp import ClientSession

logging.basicConfig(level=logging.DEBUG)

username='XXXX'
password='XXX'

async def main():
  async with ClientSession(headers={'Connection': 'keep-alive'}) as session:
    conn = Connection(session, username, password, True)
    await conn.doLogin()

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```

And then I got little bit more debug logs. But i don't know if it help you..

``` text
DEBUG:asyncio:Using selector: EpollSelector
INFO:skodaconnect.connection:Init Skoda Connect library, version 1.1.20
DEBUG:skodaconnect.connection:Using service https://msg.volkswagen.de
INFO:skodaconnect.connection:Initiating new login
DEBUG:skodaconnect.connection:Starting authorization process for client skoda
DEBUG:skodaconnect.connection:Get authorization page: "https://identity.vwgroup.io/oidc/v1/authorize"
DEBUG:skodaconnect.connection:Got authorization endpoint: "https://identity.vwgroup.io/signin-service/v1/signin/f9a2359a-b776-46d9-bd0c-db1904343117@apps_vw-dilab_com?relayState=248a031f67cf0149f4a8de9a87cc8a47e16299e1"
DEBUG:skodaconnect.connection:Got redirect to signin-service
DEBUG:skodaconnect.connection:Extracted form attribute: ('_csrf', '936cec8c-f8c1-4c22-a031-f532c9ae803a')
DEBUG:skodaconnect.connection:Extracted form attribute: ('relayState', '248a031f67cf0149f4a8de9a87cc8a47e16299e1')
DEBUG:skodaconnect.connection:Extracted form attribute: ('hmac', '21189ed3729cb3e09b054cdc6c332a8d6ded738556af373d851081adf6ca01f5')
DEBUG:skodaconnect.connection:Start authorization for user XXXXXXX
DEBUG:skodaconnect.connection:Found dynamic credentials form, extracting attributes
DEBUG:skodaconnect.connection:JSON: {'clientLegalEntityModel': {'clientId': 'f9a2359a-b776-46d9-bd0c-db1904343117@apps_vw-dilab_com', 'clientAppName': 'ŠKODA App & Portal', 'clientAppDisplayName': 'ŠKODA App & Portal', 'legalEntityInfo': {'name': 'ŠKODA', 'shortName': 'SKODA', 'productName': 'ŠKODA ID', 'theme': 'skoda', 'defaultLanguage': 'cs', 'termAndConditionsType': 'DEFAULT', 'legalProperties': {'revokeDataContact': 'DPOffice@skoda-auto.cz', 'imprintText': 'IMPRINT', 'countryOfJurisdiction': 'CZ'}}, 'imprintTextKey': 'imprint.link.text'}, 'template': 'loginAuthenticate', 'hmac': 'f78d9d11a3281e33f0706cbb71452730df228892170b5ae37f159c98202d39a4', 'useClientRendering': True, 'emailPasswordForm': {'@class': 'com.volkswagen.identitykit.signin.web.flows.base.model.EmailPasswordForm', 'email': 'XXXXX', 'password': None}, 'error': None, 'relayState': '248a031f67cf0149f4a8de9a87cc8a47e16299e1', 'nextButtonDisabled': False, 'enableNextButtonAfterSeconds': 0, 'postAction': 'login/authenticate', 'identifierUrl': 'login/identifier'}
DEBUG:skodaconnect.connection:Finalizing login
DEBUG:skodaconnect.connection:Using login action url: "https://identity.vwgroup.io/signin-service/v1/f9a2359a-b776-46d9-bd0c-db1904343117@apps_vw-dilab_com/login/authenticate"
WARNING:skodaconnect.connection:Login failed, the terms and conditions might have been updated and need to be accepted. Login to https://www.skoda-connect.com and accept the new terms before trying again
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/skodaconnect/example.py", line 23, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/skodaconnect/example.py", line 19, in main
    await conn.doLogin()
  File "/usr/local/lib/python3.10/dist-packages/skodaconnect/connection.py", line 136, in doLogin
    return await self._authorize('skoda')
  File "/usr/local/lib/python3.10/dist-packages/skodaconnect/connection.py", line 229, in _authorize
    raise SkodaEULAException('The terms and conditions must be accepted first at "https://www.skoda-connect.com/"')
skodaconnect.exceptions.SkodaEULAException: The terms and conditions must be accepted first at "https://www.skoda-connect.com/"
```

**Comment by vaclav-steiner** [comment] 2022-07-26 13:45
Hi,

I have researched the login process until it ends with an error "terms and conditions".

When I manually go through "https://identity.vwgroup.io/oidc/v1/authorize", get CLIENT_ID and relayState params, set https://identity.vwgroup.io/signin-service/v1/signin/$CLIENT_ID?relayState=$relayState" and use email with password, then I tries to call URL https://identity.vwgroup.io/signin-service/v1/$CLIENT_ID/terms-and-conditions?relayState=$relayState

There I can accept terms and conditions but it ends up with an unexpected error :-( 

The interesting thing is that if I try this steps with the newly created skoda ID few minutes ago ... I receive terms to my e-mail. But doesn't help with login...

It looks like the term and conditions that's not a problem, they are probably already agreed.

Did any of you come up with anything new please?

Thanks

**Comment by Farfar** [comment] 2022-07-26 19:02
> Hi,
> 
> I have researched the login process until it ends with an error "terms and conditions".
> 
> When I manually go through "https://identity.vwgroup.io/oidc/v1/authorize", get CLIENT_ID and relayState params, set https://identity.vwgroup.io/signin-service/v1/signin/$CLIENT_ID?relayState=$relayState" and use email with password, then I tries to call URL https://identity.vwgroup.io/signin-service/v1/$CLIENT_ID/terms-and-conditions?relayState=$relayState
> 
> There I can accept terms and conditions but it ends up with an unexpected error :-(
> 
> The interesting thing is that if I try this steps with the newly created skoda ID few minutes ago ... I receive terms to my e-mail. But doesn't help with login...
> 
> It looks like the term and conditions that's not a problem, they are probably already agreed.
> 
> Did any of you come up with anything new please?
> 
> Thanks

Sorry but no, I haven't been able to reproduce the error.
I suggest you join the discord and we can take it from there. I can create a debugging branch for you to test but what would expedite things would be if I can use a non working login to test with.

**Comment by vaclav-steiner** [comment] 2022-07-26 20:10
> Sorry but no, I haven't been able to reproduce the error. I suggest you join the discord and we can take it from there. I can create a debugging branch for you to test but what would expedite things would be if I can use a non working login to test with.

No problem to try to find the fix together.

But - trouble with terms you can reproduce with new ŠKODA ID. Could you please try to register new one and test it? No need to insert VIN and do the car registration. I tried this today and checked with your example code from last version. Same error as when I try it with my main ŠKODA ID with paired car.

Thank you

**Comment by DLHN-cz** [comment] 2022-07-28 09:54
If you find some solution, please share it also here, thanks ;) Vaclav has probably more time possibilities than me and replies much faster then me. But in case of some more logs etc. don't hesitate to ask me too ;)

**Comment by vaclav-steiner** [comment] 2022-08-01 12:01
Hi, unfortunately after various attempts I did not progress anywhere and I got stuck :-( Still I got error with terms...

I tried to debug URL calls from browser (using firefox plugin http-tracker) when I go through to login proccess. Then I tried to manually call GET and POST requests manually (using firefox plugin RESTer) and check responses. Everything look well. When using browser, after send password I got 302 redirect to https://identity.vwgroup.io/oidc/v1/oauth/sso. When I try the same from integration I got 303 redirect and URL with terms and conditions. The only difference I noticed is that the browser sends cookies with each request.

@Farfar Have you tried it with a new skoda id account please? Thanks.

**Comment by Farfar** [comment] 2022-08-03 13:00
@vaclav-steiner when I try with newly registered Skoda Connect user, email at live.com domain, I don't get the T&C error but an expected "unexpected error" since the user don't have any registered cars and thus can't authorize for the required scope.

The integration also use cookies for all requests.

**Comment by vaclav-steiner** [comment] 2022-08-03 13:35
@Farfar Interesting, thanks for your test. But that's not how it works for me :-( I try it with newly registered Skoda connect user now. Using email at hotmail.com (same provider like live.com) but same error. Same error with gmail.com and my personal domain at .cz tld.

I sent you by email these test credentials. Could you test it from you? Probably is the problem on my side ...

Thank you

**Comment by vaclav-steiner** [comment] 2022-08-18 05:23
We came up with a workaround on the discord channel yesterday. Apparently this problem only affects iphone users. Missing EULA appears after login using "MySkoda" application on android device or using any android emulator (i tried e.g. https://www.android-x86.org/). After confirmation in the android app, home assistant integration already works.

**Comment by Farfar** [comment] 2022-08-18 08:27
Until the integration is fixed with an interactive section to accept terms directly in config flow everyone can use the workaround from @vaclav-steiner!

**Closed by Farfar** 2022-08-18 08:27 UTC
Labels: bug

**Comment by DLHN-cz** [comment] 2022-08-18 08:31
hmmm, not at all. In my oppinion the problem is cross-platform. E.g. I'm not an iphone user. I'm trying to get the EULA on web or on android app, but it's not asked on both platforms (probably due to I already accept it on both). 
But this workaround you found maybe will work vice versa - I have to try to login on iphone app... Unfortunatelly I don't have access to any :(

**Comment by Farfar** [comment] 2022-08-18 14:29
> hmmm, not at all. In my oppinion the problem is cross-platform. E.g. I'm not an iphone user. I'm trying to get the EULA on web or on android app, but it's not asked on both platforms (probably due to I already accept it on both). But this workaround you found maybe will work vice versa - I have to try to login on iphone app... Unfortunatelly I don't have access to any :(

What error do you get in the integration?

**Comment by DLHN-cz** [comment] 2022-08-18 18:18
The same as above, I have to confirm EULA. And I am unable to confirm it on the website or in the app (android) due to they're not asking for. 
BUT! It seems Skoda released new version of eula and I was able to accept them directly in android app, the original one. 
So it also works for me! thanks a lot for all support.

**Comment by hanzsez** [comment] 2022-08-25 06:17
Running the latest version of the intergration, I am correctly signed on both iPhone app as well as Android app, I can login directly in Edge, Chrome or Firefox and it is not showing any EULA anythere to accept. Yet the integration still fails with "2022-08-25 08:15:16 WARNING (MainThread) [skodaconnect.connection] Login failed, the terms and conditions might have been updated and need to be accepted. Login to https://www.skoda-connect.com and accept the new terms before trying again
2022-08-25 08:15:16 ERROR (MainThread) [custom_components.skodaconnect.config_flow] Login failed with error: The terms and conditions must be accepted first at "https://www.skoda-connect.com/"

So even the suggested workaround seems to be not working 100% cases

**Comment by hanzsez** [comment] 2022-08-25 07:14
another update, so not every Nadorid is treated like Android. On Huawei phone the EULA was not shown and everything was working. Once I downloaded the android emulator referenced by vaclav I downloaded and accepted EULA in the virt environment and I was able to add the integration. So if all your phones, tablets and devices fails, try the emulator as last resort

**Comment by DLHN-cz** [comment] 2022-08-25 07:22
> another update, so not every Nadorid is treated like Android. On Huawei phone the EULA was not shown and everything was working. Once I downloaded the android emulator referenced by vaclav I downloaded and accepted EULA in the virt environment and I was able to add the integration. So if all your phones, tablets and devices fails, try the emulator as last resort

Exactly, I also fixed it by running the app in Bluestack. There the EULA was finaly displayed and after it's acceptation I was able to install the integration.
