### ISSUE TITLE
Integration can not connect to Skoda Connect

### ISSUE THREAD

**Issue by clausw45** [lendy007/homeassistant-skodaconnect#24] opened 2021-03-12 13:08 UTC
I have installed the integration via HACS. I get this error in the log:

![image](https://user-images.githubusercontent.com/72136499/110943795-eb5d4700-833b-11eb-8335-aaf6a3b3d7de.png)

Here is part of my config file:

![image](https://user-images.githubusercontent.com/72136499/111293742-e523df00-8649-11eb-9312-1f1eaa8e8391.png)

I can login to Skoda Connect webpage (although my car doesnt have Skoda Connect) and I use the MySkoda app on my phone and the phone app is working fine. I have the same user/pass for both Skoda Connect and MySkoda
What to do??

**Comment by clausw45** [comment] 2021-03-16 10:22
Anybody with an idea?

**Comment by clausw45** [comment] 2021-03-16 13:17
More log:

2021-03-16 14:10:34 WARNING (MainThread) [homeassistant.loader] You are using a custom integration skodaconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-03-16 14:10:34 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'skodaconnect'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'skodaconnect'
2021-03-16 14:10:34 WARNING (MainThread) [homeassistant.loader] You are using a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-03-16 14:10:49 ERROR (MainThread) [skodaconnect.connection] Login failed for skoda account, 'NoneType' object is not subscriptable
2021-03-16 14:10:49 WARNING (MainThread) [custom_components.skodaconnect] Could not login to Skoda Connect, please check your credentials and verify that the service is working
2021-03-16 14:10:49 ERROR (MainThread) [homeassistant.setup] Setup failed for skodaconnect: Integration failed to initialize.
2021-03-16 14:15:50 ERROR (MainThread) [skodaconnect.connection] Login failed for skoda account, 'NoneType' object is not subscriptable
2021-03-16 14:15:50 WARNING (MainThread) [custom_components.skodaconnect] Could not login to Skoda Connect, please check your credentials and verify that the service is working

**Comment by mbedk** [comment] 2021-03-17 14:01
I have the same problem

**Comment by Farfar** [comment] 2021-03-20 09:02
Duplicate of #18

**Closed by Farfar** 2021-03-20 09:02 UTC

**Comment by Farfar** [comment] 2021-03-23 14:22
> I have the same problem

Can you please check issue #18 and provide your input?
