### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by JanDetrez** [lendy007/homeassistant-skodaconnect#145] opened 2022-10-28 12:53 UTC
**Describe the bug**
I see these error logs in my Hassio log, and after that my Hassio seems to be restarting spontaneously (edit: a consecutive reboot happened once, but not all the time). Not sure if it is related, but it has been twice I've seen this log as the last one in my log.1 file

I must note though that the plugin is working correctly (it is updating values from the car).

**Latest working release**
Unclear when error started, only investigated recently because of Hassio spontaneous reboots. Current version is latest 
1.0.72

**Debug logs**
> UnboundLocalError: local variable 'last_connected' referenced before assignment
> 2022-10-28 14:22:20.449 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
>     await self._async_refresh(log_failures=True, scheduled=True)
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
>     self.async_update_listeners()
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
>     update_callback()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
>     state = self._stringify_state(available)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
>     if (state := self.state) is None:
>   File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 211, in state
>     if (is_on := self.is_on) is None:
>   File "/config/custom_components/skodaconnect/binary_sensor.py", line 53, in is_on
>     return self.instrument.is_on
>   File "/usr/local/lib/python3.10/site-packages/skodaconnect/dashboard.py", line 185, in is_on
>     return self.state
>   File "/usr/local/lib/python3.10/site-packages/skodaconnect/dashboard.py", line 169, in state
>     val = super().state
>   File "/usr/local/lib/python3.10/site-packages/skodaconnect/dashboard.py", line 59, in state
>     return self.vehicle.get_attr(self.attr)
>   File "/usr/local/lib/python3.10/site-packages/skodaconnect/vehicle.py", line 1168, in get_attr
>     return find_path(self.attrs, attr)
>   File "/usr/local/lib/python3.10/site-packages/skodaconnect/utilities.py", line 86, in find_path
>     return find_path(src[path[0]], path[1:])
> KeyError: 'parking_light'
> 2022-10-28 14:24:03.075 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
>     await self._async_refresh(log_failures=True, scheduled=True)
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
>     self.async_update_listeners()
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
>     update_callback()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
>     state = self._stringify_state(available)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
>     if (state := self.state) is None:
>   File "/config/custom_components/skodaconnect/sensor.py", line 50, in state
>     return self.instrument.state
>   File "/usr/local/lib/python3.10/site-packages/skodaconnect/dashboard.py", line 124, in state
>     val = super().state
>   File "/usr/local/lib/python3.10/site-packages/skodaconnect/dashboard.py", line 55, in state
>     if hasattr(self.vehicle, self.attr):
>   File "/usr/local/lib/python3.10/site-packages/skodaconnect/vehicle.py", line 1396, in last_connected
>     return last_connected.isoformat()
> UnboundLocalError: local variable 'last_connected' referenced before assignment
> 2022-10-28 14:24:38.157 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
>     await self._async_refresh(log_failures=True, scheduled=True)
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
>     self.async_update_listeners()
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
>     update_callback()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
>     state = self._stringify_state(available)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
>     if (state := self.state) is None:
>   File "/config/custom_components/skodaconnect/sensor.py", line 50, in state
>     return self.instrument.state
>   File "/usr/local/lib/python3.10/site-packages/skodaconnect/dashboard.py", line 124, in state
>     val = super().state
>   File "/usr/local/lib/python3.10/site-packages/skodaconnect/dashboard.py", line 55, in state
>     if hasattr(self.vehicle, self.attr):
>   File "/usr/local/lib/python3.10/site-packages/skodaconnect/vehicle.py", line 1396, in last_connected
>     return last_connected.isoformat()
> UnboundLocalError: local variable 'last_connected' referenced before assignment
> 2022-10-28 14:36:24.706 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
>     await self._async_refresh(log_failures=True, scheduled=True)
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
>     self.async_update_listeners()
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
>     update_callback()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
>     state = self._stringify_state(available)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
>     if (state := self.state) is None:
>   File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 211, in state
>     if (is_on := self.is_on) is None:
>   File "/config/custom_components/skodaconnect/binary_sensor.py", line 52, in is_on
>     return not self.instrument.is_on
>   File "/usr/local/lib/python3.10/site-packages/skodaconnect/dashboard.py", line 185, in is_on
>     return self.state
>   File "/usr/local/lib/python3.10/site-packages/skodaconnect/dashboard.py", line 169, in state
>     val = super().state
>   File "/usr/local/lib/python3.10/site-packages/skodaconnect/dashboard.py", line 55, in state
>     if hasattr(self.vehicle, self.attr):
>   File "/usr/local/lib/python3.10/site-packages/skodaconnect/vehicle.py", line 2454, in hood_closed
>     bonnet = next(item for item in doors if item['name'] == 'BONNET')
> TypeError: 'NoneType' object is not iterable

list goes on for all variables. It's unclear to me what the error means.

**Installation:**
 - Home Assistant variant: Hass OS
 - Python version: 3.10 I guess from the error logs above
 - Python library versions ["python3 -m pip list"]: where can I do this command do show this?

**Additional context**
None

**Comment by Farfar** [comment] 2022-11-18 09:40
I've never seen anything like this but I'm thinking this issue is not directly related to the integration, it seems it's data is lost between updates. Strange though if this is the only integration this happens to?
Could you try to remove and reinstall the integration?

**Comment by JanDetrez** [comment] 2022-11-21 08:13
> ing this issue is not directly related to the integration, it seems it's data is lost between updates. Strange though if this is the only integration this happens to?
> Could you try to remove and reinstall

Thanks for your reply!

It seems to be te only integration yes. My believe was that he Skoda servers were offline during those error messages, but what you mention could as well be the case. I recently reinstalled the Hassio completely, so not sure if another reinstall of the Skoda Connect component will solve anything, but worth the shot.

FYI my error log to show that all my errors are mostly related to Skoda Connect, and not other integrations/sensors.

![skod](https://user-images.githubusercontent.com/16916740/202998229-800f60d4-f7ee-4d44-b70b-3d0f431b94cc.JPG)

**Comment by JanDetrez** [comment] 2022-11-21 08:15
Also some of my sensors behaviour of last night (and another sensor (Motion Temperature) as a reference that they are not having issues)

![skod2](https://user-images.githubusercontent.com/16916740/202998518-25767d7f-351b-4b4c-94cb-18ec30889656.JPG)

**Comment by JanDetrez** [comment] 2022-11-22 07:12
Reinstall did not help unfortunately....

![image](https://user-images.githubusercontent.com/16916740/203248705-b74870bd-75b2-451b-9184-6f2aba0d1e6f.png)

**Comment by Farfar** [comment] 2022-11-22 10:11
There seem to be lots of issues with the services lately but they shouldn't affect the integration this bad. I'll review the code as soon as I can, might be that some error condition triggers which in turns "clear" some stored data.

**Comment by JanDetrez** [comment] 2022-11-22 13:54
Thank you! If you need anything on my side that can help, let me know.

**Comment by RamonQu** [comment] 2022-11-28 13:14
I've got the same issue. Trunk keeps opening and closing for example. However in the API it is stated closed. 

![image](https://user-images.githubusercontent.com/113984457/204285990-84dc6449-ea23-4005-8b64-3ad0966fc646.png)

```
28 November 2022
Was closed
14:01:20 - 10 minutes ago
Was opened
14:00:45 - 11 minutes ago
Was closed
14:00:07 - 12 minutes ago
Was opened
13:59:29 - 12 minutes ago
Was closed
13:57:35 - 14 minutes ago
Was opened
13:56:57 - 15 minutes ago
```


`2022-11-28 14:02:39.200 DEBUG (MainThread) [skodaconnect.connection] Request for "https://api.connect.skoda-auto.cz/api/v2/vehicle-status/VINSCAPED" returned with status code [200], response: {'remote': {'capturedAt': '2022-11-27T10:47:18.537Z', 'status': {'open': 'NO', 'locked': 'YES'}, 'mileageInKm': 3050.0, 'doors': [{'name': 'BONNET', 'status': 'CLOSED'}, {'name': 'TRUNK', 'status': 'LOCKED'}, {'name': 'REAR_RIGHT', 'status': 'LOCKED'}, {'name': 'REAR_LEFT', 'status': 'LOCKED'}, {'name': 'FRONT_RIGHT', 'status': 'LOCKED'}, {'name': 'FRONT_LEFT', 'status': 'LOCKED'}], 'windows': [{'name': 'SUN_ROOF', 'status': 'CLOSED'}, {'name': 'ROOF_COVER', 'status': 'UNSUPPORTED'}, {'name': 'SUN_ROOF_REAR', 'status': 'UNSUPPORTED'}, {'name': 'FRONT_LEFT', 'status': 'CLOSED'}, {'name': 'FRONT_RIGHT', 'status': 'CLOSED'}, {'name': 'REAR_LEFT', 'status': 'CLOSED'}, {'name': 'REAR_RIGHT', 'status': 'CLOSED'}], 'lights': {'overallStatus': 'OFF', 'lightsStatus': [{'name': 'RIGHT', 'status': 'OFF'}, {'name': 'LEFT', 'status': 'OFF'}]}}, 'local': None, 'errors': []}`


```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 211, in s
tate
    if (is_on := self.is_on) is None:
  File "/config/custom_components/skodaconnect/binary_sensor.py", line 52, in is_on
    return not self.instrument.is_on
  File "/usr/local/lib/python3.10/site-packages/skodaconnect/dashboard.py", line 185, in is_on
    return self.state
  File "/usr/local/lib/python3.10/site-packages/skodaconnect/dashboard.py", line 169, in state
    val = super().state
  File "/usr/local/lib/python3.10/site-packages/skodaconnect/dashboard.py", line 55, in state
    if hasattr(self.vehicle, self.attr):
  File "/usr/local/lib/python3.10/site-packages/skodaconnect/vehicle.py", line 2454, in hood_closed
    bonnet = next(item for item in doors if item['name'] == 'BONNET')
TypeError: 'NoneType' object is not iterable
```

The issue is also applicable to doors, sunroof, windows, doors. But not on the parking lights or External Power.

**Comment by Farfar** [comment] 2022-12-08 15:37
Please update library to 1.1.27 or newer. Integration won't get new release until I've fixed a few other issues.

**Closed by Farfar** 2022-12-08 15:37 UTC
Labels: bug
