### ISSUE TITLE
Login failed with error: The terms and conditions must be accepted first at "https://www.skoda-connect.com/"

### ISSUE THREAD

**Issue by DastyDiesel** [lendy007/homeassistant-skodaconnect#169] opened 2023-01-10 00:21 UTC
Hello,
I installed the latest version of this integration to my HA. But I'm not able to login my username and password (of course that both are OK becuase via web is possible). And in log there is visible this error:

Login failed with error: The terms and conditions must be accepted first at "https://www.skoda-connect.com/"

Any idea where can I accept? On website there is no popup for accept.

**Comment by RamonQu** [comment] 2023-01-10 10:40
This looks like a duplicate of issue  https://github.com/lendy007/homeassistant-skodaconnect/issues/142

**Comment by Farfar** [comment] 2023-01-13 09:31
> 

Try login in another browser.
Did you try the suggested solutions in [README](https://github.com/lendy007/homeassistant-skodaconnect#if-you-encounter-problems)?

**Comment by terriblefox** [comment] 2023-01-13 10:47
Expected HTML data for initial login form! is showing in the logs.

**Comment by ra-kal** [comment] 2023-01-13 12:06
Same here. I'm still not able to login :-(

**Comment by Farfar** [comment] 2023-01-13 12:06
> Expected HTML data for initial login form! is showing in the logs.

That is a completely different issue.

**Comment by Hartger87** [comment] 2023-01-13 13:33
> Expected HTML data for initial login form! is showing in the logs.

Same issue here, I noticed that my mobile app was also logged out.
After login in and signing a form, my mobile app was working again..

**Comment by terriblefox** [comment] 2023-01-13 16:14
last update fixed it for me!

**Comment by ChristophCaina** [comment] 2023-01-13 18:45
did happen to me today after updating the integration and restarting HA...
I had to accept the terms and conditions in the skoda app first - then, the integration was again able to connect.

Reloading and reconfiguring the integration does not help in that case

**Comment by Farfar** [comment] 2023-01-14 07:45
Since yesterday new consent must be given in app.

**Closed by Farfar** 2023-01-14 07:45 UTC

**Comment by ra-kal** [comment] 2023-01-16 14:29
I accepted the consent both on web page and in Android app, but I'm still not able to log in :-(

**Comment by Farfar** [comment] 2023-01-16 14:40
> I accepted the consent both on web page and in Android app, but I'm still not able to log in :-(

In that case you will need to provide some debug logs in order for me to help you.
If you have completed all consent forms and EULA but still encounter issues, please fill out a new issue.
