### ISSUE TITLE
skodaconnect integration not ready yet: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by imathijs** [lendy007/homeassistant-skodaconnect#178] opened 2023-01-15 20:33 UTC
Hi, after updating to the latest release I get keeping this the see in my integrations.

<img width="274" alt="SCR-20230115-tvg" src="https://user-images.githubusercontent.com/14072314/212565532-68f498fd-8644-456e-8219-3e2b8b49b3eb.png">

No entity is available at this moment. 

log:
2023-01-15 21:21:22.331 WARNING (MainThread) [homeassistant.config_entries] Config entry 'TMBJB7NY9MF026458' for skodaconnect integration not ready yet: 'NoneType' object has no attribute 'get'; Retrying in background

release: 1.2.3
HA: 2023.1.4
Supervisor: 2022.12.1
Operating System 9.4

**Comment by Farfar** [comment] 2023-01-15 20:42
Duplicate of #174, #175 and #176.
Login in MySkoda app and accept new consent.

**Closed by Farfar** 2023-01-15 20:42 UTC
Labels: bug
