### ISSUE TITLE
Server error after update to 2022.2.0

### ISSUE THREAD

**Issue by CrallH** [lendy007/homeassistant-skodaconnect#105] opened 2022-02-02 22:53 UTC
**Describe the bug**
After update the addon did not start. Deleted the integration
And now i get server error 500 when trying to add it back again.

![Screenshot_20220202_232221_io homeassistant companion android](https://user-images.githubusercontent.com/32394267/152251266-b4803888-54b3-4b84-9818-8218031c9572.jpg)

**Latest working release**
2021.12.10

**Debug logs**
Logger: skodaconnect.connection
Source: /usr/local/lib/python3.9/site-packages/skodaconnect/connection.py:315
First occurred: 23:38:38 (3 occurrences)
Last logged: 23:38:41

Login failed for ***************. The server might be temporarily unavailable, try again later. If the problem persists, verify your account at https://www.skoda-connect.com

Logger: skodaconnect.connection
Source: /usr/local/lib/python3.9/site-packages/skodaconnect/connection.py:1672
First occurred: 23:38:39 (2 occurrences)
Last logged: 23:38:41

Could not refresh tokens: 'connect'
Could not refresh tokens: 'skoda'

Logger: custom_components.skodaconnect.config_flow
Source: custom_components/skodaconnect/config_flow.py:113
Integration: Skoda Connect (documentation, issues)
First occurred: 23:38:41 (1 occurrences)
Last logged: 23:38:41

Fetch vehicles failed with error: Failed to set token for "skoda"

Logger: aiohttp.server
Source: data_entry_flow.py:267
First occurred: 23:38:41 (1 occurrences)
Last logged: 23:38:41

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 92, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 155, in get
    return await super().get(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 97, in get
    result = await self._flow_mgr.async_configure(flow_id)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 267, in async_configure
    raise ValueError(
ValueError: Show progress can only transition to show progress or show progress done.

**Installation:**
 ## System Health

version | core-2022.2.0
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 4.19.0-18-amd64
arch | x86_64
timezone | Europe/Stockholm

**Additional context**
I can log in to the portal from Chrome without issues.

**Comment by craigrouse** [comment] 2022-02-02 23:00
Same issue here and I haven't upgraded yet, so it's just coincidence that it stopped working when you updated (well, likely that the token was still valid before you updated, then failed when it tried to refresh after the reboot, I'm guessing). Mine stopped working this afternoon after I restarted the HA server.

**Comment by Tozzi89** [comment] 2022-02-02 23:29
Have the samme issue, I just updated the HA core, Hacs and the Skoda integration. Can’t update token for ”skoda” it says.

**Comment by cbolumar** [comment] 2022-02-03 06:08
Same here, error 500 after upgrade ha core to 2020.2.0

**Comment by szafran81** [comment] 2022-02-03 07:12
I think that the time of the HA update is just a coincidence. I've had the failed to set token errors since yestarday (so before the update came up), and after update the error stays the same.

**Comment by Makpoc** [comment] 2022-02-03 07:15
> Same issue here and I haven't upgraded yet, so it's just coincidence that it stopped working when you updated (well, likely that the token was still valid before you updated, then failed when it tried to refresh after the reboot, I'm guessing). Mine stopped working this afternoon after I restarted the HA server.

Same here. Stopped working a day before the update after regular HA restart. Doesn't seem to be related to the new HA release. Integration status shows `Retrying setup: Failed to set token for "skoda"`

**Comment by Tozzi89** [comment] 2022-02-03 07:37
Skoda did an update to their app, could that be related?

**Comment by Farfar** [comment] 2022-02-03 08:02
It was a minor change again to login form that resulted in an incorrect login URL being used. Should be fixed in latest release.

**Comment by Tozzi89** [comment] 2022-02-03 08:50
Updated and can confirn it works now, thanks for superfast fix!

**Comment by szafran81** [comment] 2022-02-03 09:00
Confirmed, working fine after fix.
Thank you.

**Comment by craigrouse** [comment] 2022-02-03 09:14
Working for me. Thanks again @Farfar for the super quick fix.

**Comment by cbolumar** [comment] 2022-02-03 09:45
+ 1    Working for me. Thanks again @Farfar for the super quick fix.

**Closed** 2022-02-03 12:33 UTC
Labels: bug
